"""
塔罗牌数据模块
包含 78 张塔罗牌（22 张大阿卡纳 + 56 张小阿卡纳）的名称、正位/逆位解读
"""

# 大阿卡纳 (Major Arcana) - 22 张
MAJOR_ARCANA = [
    {
        "id": 0, "name": "愚人", "name_en": "The Fool",
        "upright": "新的开始、冒险、自由、天真、无限可能",
        "reversed": "鲁莽、冒险、不谨慎、浪费、愚昧",
    },
    {
        "id": 1, "name": "魔术师", "name_en": "The Magician",
        "upright": "创造力、技能、自信、资源、能力",
        "reversed": "欺骗、操纵、才能浪费、诈骗、不自信",
    },
    {
        "id": 2, "name": "女祭司", "name_en": "The High Priestess",
        "upright": "直觉、潜意识、内在智慧、神秘、灵性",
        "reversed": "秘密、隐藏、直觉缺失、表面化、自私",
    },
    {
        "id": 3, "name": "女皇", "name_en": "The Empress",
        "upright": "丰饶、母性、自然、美丽、舒适",
        "reversed": "依赖、缺乏、创造力阻塞、疏离、空虚",
    },
    {
        "id": 4, "name": "皇帝", "name_en": "The Emperor",
        "upright": "权威、稳定、保护、领导力、父亲形象",
        "reversed": "专制、固执、缺乏领导力、滥用权力、软弱",
    },
    {
        "id": 5, "name": "教皇", "name_en": "The Hierophant",
        "upright": "传统、信仰、教育、精神导师、规范",
        "reversed": "叛逆、非传统、创新、打破规则、自由",
    },
    {
        "id": 6, "name": "恋人", "name_en": "The Lovers",
        "upright": "爱情、和谐、选择、关系、价值观",
        "reversed": "分离、不和谐、价值观冲突、诱惑、矛盾",
    },
    {
        "id": 7, "name": "战车", "name_en": "The Chariot",
        "upright": "胜利、意志力、决心、控制、征服",
        "reversed": "缺乏方向、失控、侵略、失败、意志薄弱",
    },
    {
        "id": 8, "name": "力量", "name_en": "Strength",
        "upright": "勇气、内在力量、毅力、耐心、自信",
        "reversed": "软弱、恐惧、自我怀疑、缺乏自信、疲劳",
    },
    {
        "id": 9, "name": "隐士", "name_en": "The Hermit",
        "upright": "内省、寻求真理、孤独、智慧、指引",
        "reversed": "孤立、孤独、迷失、退隐、偏执",
    },
    {
        "id": 10, "name": "命运之轮", "name_en": "Wheel of Fortune",
        "upright": "变化、循环、命运、转折点、好运",
        "reversed": "厄运、循环中断、失控、阻力、意外",
    },
    {
        "id": 11, "name": "正义", "name_en": "Justice",
        "upright": "公平、真相、法律、因果报应、平衡",
        "reversed": "不公、不诚实、法律问题、失衡、偏见",
    },
    {
        "id": 12, "name": "倒吊人", "name_en": "The Hanged Man",
        "upright": "暂停、牺牲、新视角、放下、等待",
        "reversed": "拖延、不愿牺牲、抗拒、停滞、固执",
    },
    {
        "id": 13, "name": "死神", "name_en": "Death",
        "upright": "结束、转变、放手、新生、循环",
        "reversed": "抗拒改变、停滞、恐惧、固守、死亡",
    },
    {
        "id": 14, "name": "节制", "name_en": "Temperance",
        "upright": "平衡、适度、耐心、和谐、融合",
        "reversed": "失衡、极端、缺乏耐心、冲突、不和谐",
    },
    {
        "id": 15, "name": "恶魔", "name_en": "The Devil",
        "upright": "束缚、物质主义、欲望、成瘾、执念",
        "reversed": "解放、觉醒、摆脱束缚、戒断、自由",
    },
    {
        "id": 16, "name": "高塔", "name_en": "The Tower",
        "upright": "剧变、崩塌、启示、觉醒、重建",
        "reversed": "避免灾难、拒绝改变、抵抗、迟来的觉悟",
    },
    {
        "id": 17, "name": "星星", "name_en": "The Star",
        "upright": "希望、灵感、平静、治愈、精神指引",
        "reversed": "绝望、失去信心、灵感枯竭、失望、幻灭",
    },
    {
        "id": 18, "name": "月亮", "name_en": "The Moon",
        "upright": "幻想、恐惧、不确定、直觉、潜意识",
        "reversed": "释放恐惧、认清现实、幻灭、焦虑消退",
    },
    {
        "id": 19, "name": "太阳", "name_en": "The Sun",
        "upright": "成功、喜悦、活力、自信、光明",
        "reversed": "暂时的阻碍、过度乐观、被遮蔽、快乐被剥夺",
    },
    {
        "id": 20, "name": "审判", "name_en": "Judgement",
        "upright": "觉醒、重生、自我评估、觉醒、召唤",
        "reversed": "自我怀疑、拒绝觉醒、犹豫、后悔、害怕",
    },
    {
        "id": 21, "name": "世界", "name_en": "The World",
        "upright": "完成、成就、圆满、旅行、整合",
        "reversed": "未完成、延迟、停滞、不完整、缺乏闭环",
    },
]

# 小阿卡纳 (Minor Arcana) - 四组牌组
SUITS = {
    "wands": {"name": "权杖", "name_en": "Wands", "element": "火", "meaning": "行动、热情、创造力、事业"},
    "cups": {"name": "圣杯", "name_en": "Cups", "element": "水", "meaning": "情感、关系、直觉、爱"},
    "swords": {"name": "宝剑", "name_en": "Swords", "element": "风", "meaning": "思想、沟通、冲突、理性"},
    "pentacles": {"name": "星币", "name_en": "Pentacles", "element": "土", "meaning": "物质、财富、工作、健康"},
}

# 小阿卡纳牌面数据 - 每套 14 张 (Ace, 2~10, Page, Knight, Queen, King)
MINOR_ARCANA = {
    "wands": [
        {"rank": "0", "name": "权杖王牌", "name_en": "Ace of Wands",
         "upright": "新的开始、灵感、创造力、潜力、冒险",
         "reversed": "延迟、缺乏灵感、计划受阻、方向不明"},
        {"rank": "2", "name": "权杖二", "name_en": "Two of Wands",
         "upright": "规划、决策、未来展望、发现、远见",
         "reversed": "害怕改变、犹豫不决、缺乏计划、不安"},
        {"rank": "3", "name": "权杖三", "name_en": "Three of Wands",
         "upright": "扩展、远见、探索、合作、进步",
         "reversed": "障碍、延迟、挫折、缺乏远见、合作不顺"},
        {"rank": "4", "name": "权杖四", "name_en": "Four of Wands",
         "upright": "庆祝、和谐、家庭、归属、稳定",
         "reversed": "不稳定、缺乏归属感、冲突、庆祝取消"},
        {"rank": "5", "name": "权杖五", "name_en": "Five of Wands",
         "upright": "竞争、冲突、分歧、挑战、激战",
         "reversed": "避免冲突、合作、妥协、和解、和平"},
        {"rank": "6", "name": "权杖六", "name_en": "Six of Wands",
         "upright": "胜利、认可、成功、自信、公共赞誉",
         "reversed": "失败、缺乏认可、自大、失势、傲慢"},
        {"rank": "7", "name": "权杖七", "name_en": "Seven of Wands",
         "upright": "防御、坚持、保护、优势、勇气",
         "reversed": "屈服、疲惫、劣势、放弃、被压倒"},
        {"rank": "8", "name": "权杖八", "name_en": "Eight of Wands",
         "upright": "快速、行动、进展、消息、旅行",
         "reversed": "延迟、缓慢、停滞、沟通不畅、阻碍"},
        {"rank": "9", "name": "权杖九", "name_en": "Nine of Wands",
         "upright": "韧性、坚持、毅力、防御、最后防线",
         "reversed": "放弃、疲惫、偏执、固执、精疲力尽"},
        {"rank": "10", "name": "权杖十", "name_en": "Ten of Wands",
         "upright": "负担、责任、压力、过度劳累、坚持",
         "reversed": "放下负担、委托、减压、释放、放弃"},
        {"rank": "page", "name": "权杖侍卫", "name_en": "Page of Wands",
         "upright": "热情、探索、自由精神、新消息、冒险",
         "reversed": "缺乏方向、拖延、计划失败、不成熟"},
        {"rank": "knight", "name": "权杖骑士", "name_en": "Knight of Wands",
         "upright": "能量、激情、冒险、冲动、勇气",
         "reversed": "冲动、鲁莽、缺乏方向、急躁、倦怠"},
        {"rank": "queen", "name": "权杖王后", "name_en": "Queen of Wands",
         "upright": "自信、热情、魅力、温暖、果断",
         "reversed": "嫉妒、自私、缺乏自信、多变、苛刻"},
        {"rank": "king", "name": "权杖国王", "name_en": "King of Wands",
         "upright": "领导力、远见、企业家、荣誉、冒险",
         "reversed": "冲动、傲慢、缺乏远见、独裁、苛刻"},
    ],
    "cups": [
        {"rank": "0", "name": "圣杯王牌", "name_en": "Ace of Cups",
         "upright": "爱的开始、情感丰沛、直觉、灵感、新关系",
         "reversed": "情感空虚、爱的阻塞、压抑、创造力枯竭"},
        {"rank": "2", "name": "圣杯二", "name_en": "Two of Cups",
         "upright": "统一、连接、关系、互爱、合作",
         "reversed": "分离、不和谐、关系破裂、信任问题"},
        {"rank": "3", "name": "圣杯三", "name_en": "Three of Cups",
         "upright": "庆祝、友谊、喜悦、社交、姐妹情谊",
         "reversed": "过度享乐、孤立、友谊破裂、嫉妒、八卦"},
        {"rank": "4", "name": "圣杯四", "name_en": "Four of Cups",
         "upright": "沉思、不满、冷漠、内省、冥想",
         "reversed": "觉醒、重获热情、行动、新机会、接纳"},
        {"rank": "5", "name": "圣杯五", "name_en": "Five of Cups",
         "upright": "失落、悲伤、遗憾、失望、悔恨",
         "reversed": "接受、释怀、向前看、宽恕、重建"},
        {"rank": "6", "name": "圣杯六", "name_en": "Six of Cups",
         "upright": "怀旧、回忆、纯真、童年、重逢",
         "reversed": "执着过去、无法前进、怀旧过度、停滞"},
        {"rank": "7", "name": "圣杯七", "name_en": "Seven of Cups",
         "upright": "选择、幻想、可能性、诱惑、愿景",
         "reversed": "专注、清晰、现实、决策、脚踏实地"},
        {"rank": "8", "name": "圣杯八", "name_en": "Eight of Cups",
         "upright": "放手、寻找真相、离开、追求、转变",
         "reversed": "恐惧改变、固执、逃避、停滞、迷失"},
        {"rank": "9", "name": "圣杯九", "name_en": "Nine of Cups",
         "upright": "满足、愿望实现、幸福、舒适、成功",
         "reversed": "不满、愿望落空、虚荣、表面快乐、匮乏"},
        {"rank": "10", "name": "圣杯十", "name_en": "Ten of Cups",
         "upright": "幸福、家庭和谐、圆满、爱、情感满足",
         "reversed": "家庭冲突、梦想破灭、不和谐、破碎"},
        {"rank": "page", "name": "圣杯侍卫", "name_en": "Page of Cups",
         "upright": "灵感、直觉、新情感、可能性、天真",
         "reversed": "情感不成熟、逃避、幻想、失望、脆弱"},
        {"rank": "knight", "name": "圣杯骑士", "name_en": "Knight of Cups",
         "upright": "浪漫、理想主义、追求、邀请、魅力",
         "reversed": "幻想破灭、嫉妒、情绪化、诱惑、不切实际"},
        {"rank": "queen", "name": "圣杯王后", "name_en": "Queen of Cups",
         "upright": "情感丰富、直觉、关怀、治愈、温柔",
         "reversed": "情感压抑、过度敏感、依赖、自我牺牲"},
        {"rank": "king", "name": "圣杯国王", "name_en": "King of Cups",
         "upright": "情感成熟、智慧、包容、冷静、外交",
         "reversed": "情绪失控、情感操纵、冷漠、压抑、愤怒"},
    ],
    "swords": [
        {"rank": "0", "name": "宝剑王牌", "name_en": "Ace of Swords",
         "upright": "突破、清晰、真理、洞察、智慧",
         "reversed": "混淆、误解、混乱、噪音、信息错误"},
        {"rank": "2", "name": "宝剑二", "name_en": "Two of Swords",
         "upright": "抉择、僵局、回避、平衡、犹豫",
         "reversed": "信息不足、做出决定、清醒、面对现实"},
        {"rank": "3", "name": "宝剑三", "name_en": "Three of Swords",
         "upright": "心碎、悲伤、痛苦、失落、背叛",
         "reversed": "释怀、疗愈、恢复、倾诉、情绪释放"},
        {"rank": "4", "name": "宝剑四", "name_en": "Four of Swords",
         "upright": "休息、恢复、沉思、冥想、放松",
         "reversed": "疲惫、焦虑、恢复不足、失眠、倦怠"},
        {"rank": "5", "name": "宝剑五", "name_en": "Five of Swords",
         "upright": "冲突、失败、屈辱、面子、损失",
         "reversed": "和解、妥协、放下过去、避免冲突"},
        {"rank": "6", "name": "宝剑六", "name_en": "Six of Swords",
         "upright": "过渡、放下、前行、疗愈、旅程",
         "reversed": "停滞、无法前进、阻力、逃避问题"},
        {"rank": "7", "name": "宝剑七", "name_en": "Seven of Swords",
         "upright": "策略、欺骗、隐瞒、狡猾、计划",
         "reversed": "承认、坦白、自省、改变策略、诚实"},
        {"rank": "8", "name": "宝剑八", "name_en": "Eight of Swords",
         "upright": "束缚、困境、自我限制、恐惧、无助",
         "reversed": "解放、新视角、觉醒、突破、释放"},
        {"rank": "9", "name": "宝剑九", "name_en": "Nine of Swords",
         "upright": "焦虑、噩梦、恐惧、痛苦、失眠",
         "reversed": "希望、放下恐惧、恢复、寻求帮助、释然"},
        {"rank": "10", "name": "宝剑十", "name_en": "Ten of Swords",
         "upright": "终结、失败、背叛、低谷、沉痛",
         "reversed": "复苏、重生、转机、反弹、学习教训"},
        {"rank": "page", "name": "宝剑侍卫", "name_en": "Page of Swords",
         "upright": "好奇心、求知、沟通、警觉、新想法",
         "reversed": "冲动、八卦、沟通不畅、轻率、不成熟"},
        {"rank": "knight", "name": "宝剑骑士", "name_en": "Knight of Swords",
         "upright": "行动、果断、雄心、勇气、进取",
         "reversed": "冲动、鲁莽、混乱、进攻性、不理智"},
        {"rank": "queen", "name": "宝剑王后", "name_en": "Queen of Swords",
         "upright": "清晰、独立、理性、洞察、诚实",
         "reversed": "冷漠、刻薄、孤立、过度理性、苛刻"},
        {"rank": "king", "name": "宝剑国王", "name_en": "King of Swords",
         "upright": "理性、权威、真理、智慧、公正",
         "reversed": "滥用权力、冷酷、不公、专制、无情"},
    ],
    "pentacles": [
        {"rank": "0", "name": "星币王牌", "name_en": "Ace of Pentacles",
         "upright": "新机遇、财富、丰盛、开始、物质",
         "reversed": "错失机会、财务困难、计划延迟、匮乏"},
        {"rank": "2", "name": "星币二", "name_en": "Two of Pentacles",
         "upright": "平衡、适应、多任务、灵活、理财",
         "reversed": "失衡、混乱、过度扩展、财务压力"},
        {"rank": "3", "name": "星币三", "name_en": "Three of Pentacles",
         "upright": "团队合作、学习、技能、规划、协作",
         "reversed": "缺乏团队精神、技能不足、计划混乱"},
        {"rank": "4", "name": "星币四", "name_en": "Four of Pentacles",
         "upright": "守财、节俭、稳定、控制、安全感",
         "reversed": "挥霍、过度节俭、吝啬、财务不稳定"},
        {"rank": "5", "name": "星币五", "name_en": "Five of Pentacles",
         "upright": "贫困、孤立、困难、担忧、匮乏",
         "reversed": "恢复、改善、精神富足、寻求帮助、转机"},
        {"rank": "6", "name": "星币六", "name_en": "Six of Pentacles",
         "upright": "慷慨、分享、慈善、平衡、给予与接受",
         "reversed": "不平等、债务、依赖、自私、吝啬"},
        {"rank": "7", "name": "星币七", "name_en": "Seven of Pentacles",
         "upright": "评估、投资、耐心、等待、长期规划",
         "reversed": "浪费、不耐、回报不足、停滞、错误投资"},
        {"rank": "8", "name": "星币八", "name_en": "Eight of Pentacles",
         "upright": "勤奋、专注、技能提升、学习、工匠精神",
         "reversed": "倦怠、缺乏动力、技能不足、粗心、停滞"},
        {"rank": "9", "name": "星币九", "name_en": "Nine of Pentacles",
         "upright": "丰盛、自律、独立、奢华、自给自足",
         "reversed": "财务问题、依赖、表面光鲜、孤独、不安全感"},
        {"rank": "10", "name": "星币十", "name_en": "Ten of Pentacles",
         "upright": "财富、传承、家族、遗产、长期成功",
         "reversed": "家族冲突、财务损失、破产、遗产纠纷"},
        {"rank": "page", "name": "星币侍卫", "name_en": "Page of Pentacles",
         "upright": "学习、勤奋、新技能、务实、新计划",
         "reversed": "拖延、缺乏进步、目标不清、不切实际"},
        {"rank": "knight", "name": "星币骑士", "name_en": "Knight of Pentacles",
         "upright": "可靠、勤奋、耐心、责任、务实",
         "reversed": "固执、停滞、无聊、缺乏冒险、懒惰"},
        {"rank": "queen", "name": "星币王后", "name_en": "Queen of Pentacles",
         "upright": "丰饶、务实、关怀、母性、安全感",
         "reversed": "依赖、忽视自我、财务焦虑、物质主义"},
        {"rank": "king", "name": "星币国王", "name_en": "King of Pentacles",
         "upright": "成功、商业头脑、财富、领导力、稳定",
         "reversed": "贪婪、挥霍、固执、物质主义、傲慢"},
    ],
}


def get_all_cards():
    """获取所有牌面的完整列表（大阿卡纳 + 小阿卡纳）"""
    cards = []
    # 大阿卡纳
    for card in MAJOR_ARCANA:
        cards.append({
            **card,
            "type": "major",
            "suit": None,
            "suit_name": "大阿卡纳",
        })
    # 小阿卡纳
    for suit_key, suit_data in SUITS.items():
        for card in MINOR_ARCANA[suit_key]:
            cards.append({
                "id": len(cards),
                "name": card["name"],
                "name_en": card["name_en"],
                "upright": card["upright"],
                "reversed": card["reversed"],
                "type": "minor",
                "suit": suit_key,
                "suit_name": suit_data["name"],
                "element": suit_data["element"],
                "suit_meaning": suit_data["meaning"],
            })
    return cards


ALL_CARDS = get_all_cards()